# -*- coding: utf-8 -*-
"""ShapeAI project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O2unlqfsZEMu_P5JpiXCaAmVOjnklGvS
"""

import requests
#import os
from datetime import datetime

api_key = 'b8ec56c7c397b79832b2e077b76212c4'
location = input("Enter the city name: ")
r = requests.get('https://openweathermap.org/current')
with open('api_link.json','wt') as f:
 f.write(r.text)
complete_api_link = "https://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key
api_link = requests.get(complete_api_link)
api_data = api_link.json()

#create variables to store and display data
temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

print ("-------------------------------------------------------------")
print ("Weather Stats for - {}  || {}".format(location.upper(), date_time))
print ("-------------------------------------------------------------")

print ("Current temperature is: {:.2f} deg C".format(temp_city))
print ("Current weather desc  :",weather_desc)
print ("Current Humidity      :",hmdt, '%')
print ("Current wind speed    :",wind_spd ,'kmph')

"""d=requests.get('https://openweathermap.org/current#current_JSON')
print(d.text)
"""